DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE ASSET (
  ASSET_NAME VARCHAR(250) PRIMARY KEY,
  TOTAL_INCIDENT INT,
  TOTAL_UP_TIME INT,
  TOTAL_DOWN_TIME INT,
  CURRENT_TIMESTAMP TIMESTAMP(250),
  RATING INT
 );

CREATE TABLE EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ASSET_NAME VARCHAR(250),
  START_TIME TIMESTAMP(250),
  END_TIME TIMESTAMP(250),
  SEVERITY INT
 );
 

COMMIT;