DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS ERROR_EVENT;
DROP TABLE IF EXISTS MEMBERS;


CREATE TABLE EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ASSET_NAME VARCHAR(250),
  START_TIME TIMESTAMP(0),
  END_TIME TIMESTAMP(0),
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  SEVERITY INT
 );

 
 CREATE TABLE ERROR_EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ERRONEOUS_RECORD VARCHAR(1000),
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
 );

 
  CREATE TABLE USER_TABLE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(1000),
  FIRST_NAME VARCHAR(1000),
  LAST_NAME VARCHAR(1000)
 );
 
 INSERT INTO USER_TABLE 
 		(USER_ID, FIRST_NAME, LAST_NAME) 
 		VALUES(254584, 'PIJUSH KANTI', 'DAS');
 INSERT INTO USER_TABLE 
 		(USER_ID, FIRST_NAME, LAST_NAME) 
 		VALUES(987856, 'DAVID', 'JAMES');
 INSERT INTO USER_TABLE 
 		(USER_ID, FIRST_NAME, LAST_NAME) 
 		VALUES(453423, 'XAVIER', 'BARDEM');
 
COMMIT;