DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS ASSET;
DROP TABLE IF EXISTS ERROR_EVENT;

CREATE TABLE ASSET (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ASSET_NAME VARCHAR(250),
  TOTAL_INCIDENT INT,
  TOTAL_UP_TIME INT,
  TOTAL_DOWN_TIME INT,
  RATING INT,
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
 );

CREATE TABLE EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ASSET_NAME VARCHAR(250),
  START_TIME TIMESTAMP(0),
  END_TIME TIMESTAMP(0),
  SEVERITY INT
 );

  CREATE TABLE ERROR_EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ERRONEOUS_RECORD VARCHAR(1000),
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
 );

COMMIT;