DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS ERROR_EVENT;


CREATE TABLE EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ASSET_NAME VARCHAR(250),
  START_TIME TIMESTAMP(0),
  END_TIME TIMESTAMP(0),
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  SEVERITY INT
 );

 
 CREATE TABLE ERROR_EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ERRONEOUS_RECORD VARCHAR(1000),
  CRR_STMP TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
 );

COMMIT;